### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #335

### CODE REVIEW

**Comment by Keruspe** [comment]
Could we get a new release with this? Without the tracing-subscriber bump, cargo audit is not happy because it depends on chrono

**Comment by o0Ignition0o** [comment]
Hey, sure, I'm going to do the publish dance tonight if it sounds good to you ?

**Comment by Keruspe** [comment]
Thanks!

**Comment by o0Ignition0o** [comment]
I was born and raised in Lyon, so according to the [quart dheure lyonnais](https://fr.wiktionary.org/wiki/quart_d%E2%80%99heure_lyonnais) i should be able to get to it soon ™️ 😅

**Comment by Keruspe** [comment]
Quite familiar with that kind of things: we also have the [quart d'heure nantais](https://fr.wiktionary.org/wiki/quart_d%E2%80%99heure_nantais)

**Comment by o0Ignition0o** [comment]
*cough cough* as promised and just in time bastion 0.4.5 is out

**Pull request merged**
