### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by oScape**
Improve a bit the readme, to join the user to see the example quicker than previously.
=> https://news.ycombinator.com/item?id=26304568
Even if the first comment exaggerates a bit, I think that putting the examples from the beginning will make it easier to orient new users towards the code and allow them to understand the project more easily.

Stuff around redundancy.

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
care to share a screenshot of the preview? otherwise lgtm :shipit:

**Comment by Stupremee** [comment]
You can click on "View File" inside the diff

**Review by Stupremee — APPROVED** [review]
Only the alignment thing is missing, otherwise lgtm

**Comment by o0Ignition0o** [comment]
yup my bad, it looks great!

**Review by o0Ignition0o — APPROVED** [review]

**Comment by oScape** [comment]
@Stupremee you are right about the alignment, it's annoying, but css are not supported:
=> https://github.community/t/github-flavored-markdown-doesnt-render-css-styles-inside-a-html-block/126258

I will find an disposition.

**Pull request merged**
