### PR TITLE
Fix extreme amount of syscalls to give time share to OS

### PR DESCRIPTION
**Pull request by vertexclique**

### CODE REVIEW

**Comment by rtyler** [comment]
As mentioned in DIscord, this commit does remove the syscall storm to `sched_yield` under the covers, but it does _not_ remove the CPU-intensive busy-loop that is happening here.

**Comment by rtyler** [comment]
with the change in 03b2dbc, this is looking good :+1:

**Comment by azastrael** [comment]
I updated `Bastion::block_until_stopped` to use a [`Condvar`](https://doc.rust-lang.org/std/sync/struct.Condvar.html) which should have near to zero CPU costs :)

**Comment by vertexclique** [comment]
Fixes #148 completely.

**Pull request merged**
